services:
  jekyll:
    image: amirpourmand/al-folio:v0.14.6
    ports:
      - "8080:8080"      # 사이트
      - "35729:35729"    # LiveReload
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    # CMD 대신 ENTRYPOINT를 완전히 교체해 0.0.0.0:8080으로 바인드
    entrypoint: >
      bash -lc "bundle install &&
                bundle exec jekyll serve
                  --host 0.0.0.0
                  --port 8080
                  --livereload
                  --livereload-port 35729
                  --watch --force_polling --verbose --unpublished --future"