source "https://rubygems.org"

gem "jekyll"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-redirect-from"
gem "jemoji"
gem "jekyll-gist"
gem "webrick"
gem "jekyll-paginate"
gem "jekyll-include-cache"
gem "faraday-retry"